#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TEMPLATE_DIR=$DIR/templates/simple-web-project/.

DESTINATION="."

if [ "$1" != "" ]; then
  DESTINATION="$1"
fi

cp -R $TEMPLATE_DIR $DESTINATION